version: "3"

tasks:
  build:
    desc: Build package
      - docker build . -t celine-eu/celine-regorus
  compile:
    desc: Build package
    cmds:
      - |
        docker run --rm \
        -v ${PWD}/dist:/app/dist \
        -v ${PWD}/main.py:/app/main.py \
        -v ${PWD}/celine_regorus_builder:/app/celine_regorus_builder \
        -v ${PWD}/stubs:/app/stubs \
        celine-eu/celine-regorus python main.py {{.CLI_ARGS}}
  exec:
    desc: exec container
    cmds:
      - docker run -it --rm -v ${PWD}/dist:/app/dist celine-eu/celine-regorus bash
